version: '3'
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - FLASK_DEBUG=${DEBUG}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./backend/datasets.sql:/docker-entrypoint-initdb.d/datasets.sql
    expose:
      - 5432
    ports:
      - 5432:${DB_PORT} # Change in the .env file if there is a conflict on your machine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
